build:
  environment:
    php:
      version: '8.0'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      before:
        - sudo apt install libyaml-dev -y
        - sudo pecl install yaml
      tests:
        override:
          - command: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
