build:
  environment:
    php:
      version: '8.0'
      pecl_extensions:
        - yaml
  nodes:
    analysis:
      dependencies:
        before:
          - sudo apt install libyaml-dev -y
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
